SerpentAI/Archipelago

- worlds/keymasters_keep/game.py
- worlds/keymasters_keep/game_objective_generator.py
- worlds/keymasters_keep/games/__init__.py
- worlds/keymasters_keep/games/a_dance_of_fire_and_ice_game.py
- worlds/keymasters_keep/games/anger_foot_game.py
- worlds/keymasters_keep/games/archipelago_multiworld_randomizer_game.py
- worlds/keymasters_keep/games/final_fantasy_xvi_game.py
- worlds/keymasters_keep/games/game_backlog_game.py
- worlds/keymasters_keep/games/halls_of_torment_game.py
- worlds/keymasters_keep/games/neon_white_game.py
- worlds/keymasters_keep/games/pinball_fx3_game.py
- worlds/keymasters_keep/games/pizza_tower_game.py
- worlds/keymasters_keep/games/placid_plastic_duck_simulator_game.py
- worlds/keymasters_keep/games/rabbit_and_steel_game.py
- worlds/keymasters_keep/games/retro_achievements_game.py
- worlds/keymasters_keep/games/star_wars_battlefront_ii_classic_game.py
- worlds/keymasters_keep/games/street_fighter_6_game.py
- worlds/keymasters_keep/games/trackmania_game.py
- worlds/keymasters_keep/games/trombone_champ_game.py
- worlds/keymasters_keep/games/ultrakill_game.py
- worlds/keymasters_keep/options.py
This will have conflicts upon every single game being added.
Likely needs additional testing as an apworld, but best to open now in case you have feedback.
> Move to AutoGameRegister and add Rabbit & Steel

- worlds/keymasters_keep/game_objective_template.py
- worlds/keymasters_keep/games/project_sekai_game.py
Did a small playtest (about ~4 trials) and it plays about how I want it to.
> KMK - Add Project Sekai and support sequences/callables for data collection amount

- worlds/keymasters_keep/games/project_sekai_colorful_stage_game.py
- worlds/keymasters_keep/games/shiny_pokemon_hunt_game.py
- worlds/keymasters_keep/options.py
I'm sorry I'm not playtesting this one.
> KMK - PRSK Revision, Fix tests, Shiny Pokémon Hunt

- worlds/keymasters_keep/games/bomberman_64_game.py
**Bomberman 64**
- New objectives involving finding or earning costume parts.
- Objectives for completing all stages in a world have been modified to instead require completing a dynamically chosen number of them for more consistent variety.
- Weights of objectives have been re-balanced.
> Update Bomberman 64

- worlds/keymasters_keep/games/trackmania_2_game.py
**Trackmania 2**
Adapts the existing Trackmania (2020) implementation for the older Trackmania 2 release. Although each environment is technically a different "game" I've chosen to implement them all together and allow environment selection via configuration.
> Add Trackmania 2

- worlds/keymasters_keep/games/hyrule_warriors_definitive_edition_game.py
Could probably make some further adjustments, but I wanna get some discussion going first.
> KMK - Revise Hyrule Warriors Definitive Edition

- worlds/keymasters_keep/games/shadow_the_hedgehog_game.py
Sorry if I screwed something up, I literally just made my github account for this.
> KMK: Fix minor typo in Shadow the Hedgehog objectives

- worlds/keymasters_keep/games/plants_vs_zombies_2_game.py
This proposal assumes you have played the entire game (Finished Adventure Mode) and maybe have done most of the Vasebreaker Levels (except Endless).
- Since BWB, NMT and JM are considered the harder worlds in the game, I have split them 30/70%, the first 30% being not too difficult and the other 70% being difficult, thus locked behind #Difficult.
- Modern Day however is on a whole other level and get #Difficult automatically.
- I have only written the Free Plants down, since premium plants either cost gems, real world money or intense grinding at the Arena. If the player has them, they are free to use them.
- I have split the plants into their own Plant Families, however I have not used all the families, either because I want the player to have the choice or couldn't find a way to fit it …
> KMK: Plants vs Zombies 2

- worlds/keymasters_keep/games/rimworld_game.py
Adding support for Rimworld to Keymaster's Keep.
WARNING: This game is an After Dark rated game. This is reflected by the "adult or unrated" tag in the implementation itself. 
I hope that this implementation is significantly better than my first attempt with Salt and Sacrifice. Less work for you the more I learn after all.
> Add Rimworld to KMK

- worlds/keymasters_keep/games/final_fantasy_xiv_game.py
**Final Fantasy XIV**
* Added new objectives for Treasure Hunts and Treasure Dungeons.
* Added new objectives for Adventuring Forays Eureka and Bozja.
* Added two jumping puzzles from Dawntrail.
* Defined properties for common conditionals in an effort to prevent potential for typos in string comparisons.
> Update Final Fantasy XIV

- worlds/keymasters_keep/games/trackmania_turbo.py
> KMK: Add TrackMania Turbo

- worlds/keymasters_keep/games/super_mario_galaxy_2_game.py
This implementation assumes you've 100% the game (all 242 stars).
- I split the Power Stars and Green Stars into their seperate categories, so if the player just wants to hunt Power Stars or just Green Stars, or both, they can.
- I don't really have too much to add that I haven't already said in the Super Mario Galaxy 1 Implementation, as both games are pretty similar. (Who would have figured?)
If anyone that has played SMG2 wants to add their own ideas or rebalance some things, feel free to!
> KMK: Super Mario Galaxy 2 Implementation

- worlds/keymasters_keep/games/fourteen_minesweeper_variants_game.py
Updates 14 Minesweeper Variants to have an option to include combinations and bonus variants.
Also adds optional objectives.
> KMK: Update 14 Minesweeper Variants

- worlds/keymasters_keep/games/battleblock_theater_game.py
Adds BattleBlock Theater to Keymaster's Keep
> KMK: Add BattleBlock Theater

- worlds/keymasters_keep/games/mega_man_1_game.py
Adds support for Mega Man 1 to Keymaster's Keep.
Generated a test game, viewed that various objectives displayed correctly in the client.
> KMK: Add support for Mega Man 1

- worlds/keymasters_keep/games/mega_man_2_game.py
Adds support for Mega Man 2 to Keymaster's Keep.
Ran a few test gens with different options and viewed that they displayed correctly in the client.
> KMK: Add support for Mega Man 2

- worlds/keymasters_keep/games/mega_man_3_game.py
Adds support for Mega Man 3 to Keymaster's Keep.
Ran a few test gens with different options and viewed that they displayed correctly in the client.
> KMK: Add support for Mega Man 3

- worlds/keymasters_keep/games/mega_man_4_game.py
Adds support for Mega Man 4 to Keymaster's Keep.
Ran a few test gens with different options and viewed that they displayed correctly in the client.
> KMK: Add support for Mega Man 4

- worlds/keymasters_keep/games/dead_by_daylight_game.py
Please format your title with what portion of the project this pull request is
targeting and what it's changing.
ex. "DBD: Fixed missing survivors"
Added the 5 base game survivors that I originally overlooked.
Downloaded the new zip, made it an apworld, tested in client.
> DBD - Added base 5 Survivors

- worlds/keymasters_keep/games/shadow_the_hedgehog_game.py
It wasn't, so if you could double-check my optional objective change's syntax, that would be great.
> Make Shadow the Hedgehog's objectives less strict

- worlds/keymasters_keep/games/league_of_legends_game.py
Cassiopeia does not have legs, therefore we do not want to have a boots challenge on her.
> KMK: Check for legs in League of Legends
