SerpentAI/Archipelago

worlds/keymasters_keep/games/bomberman_64_game.py

Resolves an issue with the weighting of one objective being far too high. Also fixes grammar of the Archipelago option description.

Bomberman 64 Weight fix

---

worlds/keymasters_keep/games/mario_party_2_game.py

Adds Mario Party 2 to Keymaster's Keep. Objectives are fairly straightforward. All board-based objectives are considered time consuming due to the nature of the game. Weighting most heavily favors Mini-Game objectives since those have the highest variety (and being asked to do multiple Mario Party board games per keep would be really long)

Add Mario Party 2 to Keymaster's Keep

---

worlds/keymasters_keep/client_gui/client_gui.py
worlds/keymasters_keep/client_gui/client_gui_layouts.py

When I was initially checking out KK, it wasn't clear to me that the checks were in a separate tab. My first instinct was to click the "X trials" text by the game name, which didn't do anything. 
So this PR makes it clickable. When it's clicked, it switches to the "Available Trials" tab.
Generated a single game (SF6) KK locally and connected via the KK client, then clicked multiple keep areas and unlocks to ensure that all 3 states for keep areas functioned without error.
(The only graphical change was the "Game: Street Fighter 6    X trials" text color, to hopefully better convey that it's now clickable. No preference on colors for this, so feel free to suggest/change after.)

Client: Clicking game name and "X trials" message navigates to "Available Trials" tab

---

worlds/keymasters_keep/games/mario_party_2_game.py

Fixes one instance where "a" would be potentially used before a word with a vowel ("a Easy Course") and a minor mistake in a comment

Minor typo fixes for Mario Party 2

---

worlds/keymasters_keep/games/pokemon_rse_game.py

Major overhaul to Pokémon Ruby, Sapphire, and Emerald Versions. The following (non-comprehensive) changes have been made:
- Adds "Shiny Hunting" as an objective type. All objectives in this category are considered time consuming, and the entire category is off by default. Generation 3 does not feature any specific methods of increasing shiny odds outside of RNG manipulation, so this should not be a default category. Additionally, all objectives are weighted in such a way that they are unlikely to appear when combined with other categories. All shiny hunting objectives are time consuming, with the objective to encounter or obtain a specific Shiny also being considered difficult.
- As a note, I had already added this before the new Shiny Hunting metagame was added. I still feel this has a …

KK: Pokémon RSE v2

---

worlds/keymasters_keep/games/final_fantasy_xiv_game.py

**Final Fantasy XIV**
Adds support for Final Fantasy XIV.  This is a highly modular implementation, allowing the player to pick and choose from a variety of in-game activities with which to populate their objective list. Cases of empty configurations will cause some sane defaults to populate the objective list.
Implementation includes activities for:
- FATEs
- Guildhests
- The Hunt
- Dungeons
- Trials (Normal and Extreme)
- Raids (Normal, Savage, and Alliance)
- Deep Dungeons
- Variant Dungeons
- Limited Jobs
- PvP (Crystalline Conflict, Frontline, and Rival Wings)
- Gathering
- Fishing
- Crafting
- Jumping Puzzles
- Gold Saucer Activities
- Triple Triad
- Miscellaneous Minigames
- Unreasonable Tasks
This wide variety should allow for quite varied objectives when enabled. Alternatively, …

Add Final Fantasy XIV

---

worlds/keymasters_keep/games/guitar_hero_5_game.py
worlds/keymasters_keep/games/guitar_hero_ii_game.py
worlds/keymasters_keep/games/guitar_hero_warriors_of_rock_game.py
worlds/keymasters_keep/games/guitar_hero_world_tour_game.py

You knew these were coming. GH2 has toggles for bonus tracks and X360 exclusives, the other ones have straight setlists so no options needed there.

Add Guitar Hero II, World Tour, 5, and Warriors of Rock

---

worlds/keymasters_keep/games/creeper_world_3_arc_eternal_game.py

- Add 2 extra objectives for variety
- Change DMD mission challenges to now only mention enemy types and count giving room for players to adjust some of the other settings to ensure playability
- Change Data points for Enemies as Digitalis and Runners require Emitters to be present to function properly
- Add challenge for DMD specifically to use the Next Crazy option which rolls completely random settings for almost all DMD options.
Generated few games with KeymasterKeep and see how challenges / optionals look like

Keymasters Keep, update to Creeper World 3 Arc Eternal

---

worlds/keymasters_keep/games/mages_of_mystralia_game.py

- Add extra challenge to go and find a number of spell runes. This may involve multiple boss fights or reaching near end game state
- Adjusted difficulty or time_consuming flags for challenges involving the adventure, generally they will take significantly longer than whatever hall of trials throws at us or for some involve multiple boss fights
Generated several Key Master Keep games and see how challenges / optionals look like

Keymasters Keep, update to Mages of Mystralia

---

worlds/keymasters_keep/games/advance_wars_days_of_ruin_game.py

- Add optional objective to rank up a random combat capable unit
- Correct freeplay 2p maps to not include 3p and 4p maps as there is no way to play these maps with less than the amount of players they are made for
Tested by generating KeyMaster Keep a few times to see how the challenges look like

Keymasters Keep, update to Advance Wars Days of Ruin

---

worlds/keymasters_keep/games/salt_and_sacrifice.py

Proposing an implementation of Salt and Sacrifice for Keymaster's Keep. This is a 2D Souls-like Metroidvania based around exploring new regions with equipment and completing bosses rushes by killing "Mages". This is intended to create a series of objectives to randomize kill order and occasionally the equipment required to do so.

Salt and Sacrifice: implement new game

---

worlds/keymasters_keep/games/guilty_gear_strive_game.py

**GUILTY GEAR -STRIVE-**
Adds support for Guilty Gear -Strive-. This implementation focuses on offline-only challenges, largely dealing with versus matches against CPUs and occasional extra constraints such as winning a round without taking damage, or doing so without expending any Tension gauge.
Clearing through a randomly chosen Survival mode stage serves as a potentially time-consuming objective. While it would be possible to greatly increase the range on this objective, the time needed to go through potentially 30 stages is already much higher than all other objectives.

Add Guilty Gear Strive

---

worlds/keymasters_keep/games/final_fantasy_xiv_game.py

**Final Fantasy XIV**
* Combat objectives modified to specify optional job selection between two choices.
* Updated the labels for multiple objectives for clarity.
* Missing weights in some objectives have been added.
* Weights rebalanced for some objectives.
* Chaotic Alliance Raid added as selectable content type.
* Added objectives related to the Firmament for Gatherers, Crafters, and Fishers.
* Resolved an issue where Big Fish from expansions were not being considered for objectives.

Update Final Fantasy XIV

---

worlds/keymasters_keep/games/mario_kart_8_game.py

Separates out Mario Kart 8 Deluxe and Wii U DLC content, allowing the implementation to work with the base Wii U version, or the Wii U version with any combination of its DLCs. When MarioKart8IsDeluxe is set to true (which it is by default, as it is the most common version) the Wii U DLC list is ignored and the content is added to the game regardless. Similarly, when MarioKart8IsDeluxe is set to false, the Booster Course content is not added regardless of whether the DLC is set.

Mario Kart 8: Add support for Wii U version

---

worlds/keymasters_keep/games/pokemon_rse_game.py

New option adds additional challenges or challenge variations to existing categories.
- Adds Legendary and other one-offs to catching and battling challenges, as well as to the available Pokémon list for optional objectives.
- All stone Pokémon are considered one-offs for this purpose, due to the difficulty involved in acquiring additional stones without restarting the game (Moon Stone in particular is only repeatable at all in Sapphire)
- Adds Gym Leader fights to the battle category
- Adds new trainer battle objective: `using no more Pokémon than your opponent`
- Various cleanup to wording and code

Pokémon RSE: Add new option to allow objectives that are once per save

---

worlds/keymasters_keep/games/lego_rock_band_game.py
worlds/keymasters_keep/games/rock_band_2_game.py
worlds/keymasters_keep/games/rock_band_3_game.py
worlds/keymasters_keep/games/rock_band_4_game.py
worlds/keymasters_keep/games/rock_band_game.py

Adds Rock Band 1 through 4 and Lego Rock Band. Two games (3 and Lego) have NDS-only switches because those releases are funny, otherwise they're all very direct implementations of the same concept from the Guitar Hero series.

Add 5 Rock Band games

---

worlds/keymasters_keep/games/bomberman_64_game.py

**Bomberman 64**
* Rebalance weights to reduce frequency of the lengthier objectives.
* Added new objectives for earning the gold card for defeating 30 enemies from eligible stages.
* Objectives for earning a number of gold cards from a stage now have a minimum of two gold cards.
* Objectives for completing a number of stages in a world now have a minimum of two stages.
* Objectives which required finding multiple costume items have been removed in favor of a higher weight for finding single costume items.

Update Bomberman 64

---

worlds/keymasters_keep/games/realm_of_the_mad_god_game.py

A small handful of dungeons cannot ever reasonably drop stat-increasing potions, and thus are not valid options for the potion drop objective. This was an oversight that I missed in the game proposal.
I fixed this by removing those dungeons from the main cached properties and putting them in dedicated ones. "dungeons_with_pots" runs as the old dungeons method did, with a new command taking the name "dungeons" which runs dungeons_with_pots and extends the list with the few potless dungeons. The objectives that don't care about pots one way or another should hook into this.
Also fixed: a stray space in a string "Candyland Hunting Grounds" has been deleted.

Fix logic bug for RotMG

---

worlds/keymasters_keep/games/super_mario_galaxy_game.py

This implementation assumes you've collected all 120 Power Stars with Mario.
- For the Optional Game Constraints, some of these might be impossible so I locked them behind #Difficult.
- A few Purple Comets are marked as #Time-Consuming, I'm looking at you "Purple Coins by the Seaside in Sea Slide Galaxy".
- I've marked what I feel are somewhat difficult missions with #Difficult. Feel free to tell me I have a skill issue for some of these.
- If the Galaxy has more than one star, it'll have the (Star Number) in the name; it's also split per area.
- Grand Star Rescue is actually replayable. For those who don't know, after you have done Gateway's Purple Coins in Gateway Galaxy (the Red Star), if you revisit it, it'll pop up a level select that lets you redo the first ever star in the game!
- …

KMK: Not accidentally closing Super Mario Galaxy Implementation

---

worlds/keymasters_keep/games/little_inferno_game.py

This implementation assumes you've unlocked every catalog and potentially bought every item at least once. Having achieved all the combos is optional but will help you achieve the challenge faster instead of guessing the hint with the combo's name.
- DLC adds a new catalog and 51 combos, so I made it an "if else" case. The 8th catalog is available near the start and gradually unlocks new items as you progress with the game. If the DLC is enabled, combos go back and forth between vanilla combos and DLC combos. (so their ID's/index gets moved around, thus opted for a range, more info further down)
- I made the catalogs pull from a range, so you will have to burn anywhere from 3 to 5 items per catalog challenge.
- Shopping Spree challenge makes you buy 1 item from each catalog, going in …

KMK: Little Inferno Implementation

---

worlds/keymasters_keep/games/plants_vs_zombies_game.py

Here's what I changed:
- Adventure Mode has a toggle now, you can enable or disable in the yaml template.
- I only kept a few achievements that are mainly "survive type of level without essential plant group". I also kept Sunny Days since I feel that's an interesting challenge, generating 8000 sun in a level. They are no longer time-consuming. You could do these in conjunction with an easy Survival mode as a house rule.
- I added a few Zen Garden challenges, most are relatively easy.
- Reimplemented Survival mode, the hard levels are not really that much harder so I kept them all in the same list.
- I, Zombie and Vasebreaker Endless now pick from 3 to 8 as the streak you need to reach.
- Survival Endless picks from 10 to 20; since Survival Endless counts Flags as the streak. This means …

KMK: Tweaked plants_vs_zombies_game.py

---

worlds/keymasters_keep/games/kingdom_hearts_melody_of_memory_game.py

Added `kingdom_hearts_melody_of_memory_include_world_tour` to game options. 
This allows the player to choose whether objectives regarding the World Tour mode of the game are included. Per default this option is set to `true`.

KH MoM: Add option to exclude World Tour mode

---

worlds/keymasters_keep/enums.py

The location names beginning with "Beyond the Enigmatic Portal" have an erroneous space between that name and the colon indicating the trial they're for. This removes that space.
I ran a test gen and observed that the typo had been removed.
Before:
After:

KMK: Fixed Enigmatic Portal Typo

---

worlds/keymasters_keep/games/spore_game.py

Adds new names & one mission rename under the Sporecast missions category
Noticed when opening up Spore & checked wikipedia that the adventures were official created by Maxis and not by a third party. Kinda, by Robot Chicken writers. But the adventure itself was made by "Maxis" classifying it as a Maxis official adventure that can be found via sporecast.
As well as renamed one adventure to accurately match the ingame adventure name.
I also want the Space exclusive missions to no longer be "Time Consuming" the reason is with the mission that you have, the game assumes you have the mission available. Not sure how to remove that in the code without breaking it. So I figured if you would be able to do that for me on top of approving this PR, I would appreciate it.

KMK: Sporecast Missions update

---

worlds/keymasters_keep/games/tower_unite_game.py

I've updated tower_unite_game.py from 0.18.5.1 to 0.18.7.0, here's what I changed:
- Added more Accelerate Challenges. You can now play every track on Mirror mode and newly added Unit routes are present for both modes.
- Added Lookout to the list of SDNL maps
- Added The Shooting Gallery to Boardwalk
- Added Corn of the Dead to Arcade

KMK: Update tower_unite_game.py

---

worlds/keymasters_keep/game_objective_template.py

This catches two of the most common errors thrown by `random.sample`, and:
* In the case of a set, converts it to a list so it can be sampled
* In the case of an empty collection, raise a more user-friendly error message so that it can be better debugged

A bit of sanitisation of collections
